window.Game = window.Game || {};

Game.Config = {
  // Grid (world-space logic grid)
  TILE_SIZE: 48,
  GRID_COLS: 20,
  GRID_ROWS: 14,

  // Isometric projection
  ISO_TILE_W: 64,
  ISO_TILE_H: 32,

  // Tile types
  TILE: {
    BLOCKED: 0,
    BUILDABLE: 1,
    PATH: 2,
    ENTRY: 3,
    EXIT: 4,
  },

  // Game balance
  STARTING_GOLD: 200,
  STARTING_LIVES: 20,
  INTEREST_RATE: 0.02,
  INTEREST_CAP: 20,
  EARLY_START_BONUS: 0.10,
  SELL_REFUND_RATE: 0.60,
  WAVE_HP_SCALING: 1.08,
  WAVE_GOLD_SCALING: 1.03,
  BETWEEN_WAVE_TIME: 15,
  BOSS_LIFE_COST: 5,

  // Upgrade scaling per level
  UPGRADE_DAMAGE_MULT: 1.40,
  UPGRADE_RANGE_MULT: 1.15,
  UPGRADE_RATE_MULT: 0.80, // lower is faster
  UPGRADE_COST_MULT: 0.60, // fraction of cumulative cost
  MAX_TOWER_LEVEL: 3,

  // Tower definitions
  TOWERS: {
    arrow: {
      name: 'Arrow Tower',
      cost: 50,
      range: 150,
      fireRate: 0.4,
      damage: 8,
      color: '#8B6914',
      projectileSpeed: 500,
      projectileColor: '#8B6914',
      canHitFlying: true,
      special: null,
      description: 'Fast, reliable damage',
      l3: 'Double shot',
    },
    cannon: {
      name: 'Cannon Tower',
      cost: 100,
      range: 120,
      fireRate: 1.5,
      damage: 40,
      color: '#555555',
      projectileSpeed: 350,
      projectileColor: '#333333',
      canHitFlying: false,
      special: 'splash',
      splashRadius: 60,
      description: 'Slow, AoE splash damage',
      l3: 'Stun 0.5s on hit',
    },
    frost: {
      name: 'Frost Tower',
      cost: 75,
      range: 130,
      fireRate: 0.8,
      damage: 5,
      color: '#88CCEE',
      projectileSpeed: 400,
      projectileColor: '#AADDFF',
      canHitFlying: false,
      special: 'slow',
      slowAmount: 0.40,
      slowDuration: 2.0,
      description: 'Slows enemies',
      l3: '60% slow, 3s duration',
    },
    lightning: {
      name: 'Lightning Tower',
      cost: 125,
      range: 160,
      fireRate: 1.0,
      damage: 25,
      color: '#FFD700',
      projectileSpeed: Infinity,
      projectileColor: '#FFFF44',
      canHitFlying: true,
      special: 'chain',
      chainCount: 3,
      chainRange: 80,
      description: 'Chains to nearby enemies',
      l3: 'Chains to 5 enemies',
    },
    sniper: {
      name: 'Sniper Tower',
      cost: 150,
      range: 250,
      fireRate: 2.5,
      damage: 80,
      color: '#8B0000',
      projectileSpeed: 800,
      projectileColor: '#FF4444',
      canHitFlying: true,
      special: 'pierceArmor',
      description: 'Long range, ignores armor',
      l3: '25% crit chance (2x)',
    },
    flame: {
      name: 'Flame Tower',
      cost: 100,
      range: 90,
      fireRate: 0.1,
      damage: 1.5,
      color: '#FF6600',
      projectileSpeed: 0,
      projectileColor: '#FF4400',
      canHitFlying: false,
      special: 'cone',
      coneAngle: Math.PI / 3,
      dotDamage: 3,
      dotDuration: 3.0,
      description: 'Continuous AoE cone, burn DoT',
      l3: 'Increasing damage over time',
    },
  },

  // Tower build order for UI
  TOWER_ORDER: ['arrow', 'cannon', 'frost', 'lightning', 'sniper', 'flame'],

  // Enemy definitions
  ENEMIES: {
    goblin: {
      name: 'Goblin',
      hp: 30,
      speed: 80,
      armor: 0,
      gold: 5,
      color: '#44AA44',
      radius: 8,
      flying: false,
    },
    soldier: {
      name: 'Soldier',
      hp: 80,
      speed: 50,
      armor: 3,
      gold: 10,
      color: '#888888',
      radius: 10,
      flying: false,
    },
    wolf_rider: {
      name: 'Wolf Rider',
      hp: 50,
      speed: 130,
      armor: 0,
      gold: 12,
      color: '#8B5A2B',
      radius: 9,
      flying: false,
      shape: 'diamond',
    },
    knight: {
      name: 'Knight',
      hp: 200,
      speed: 40,
      armor: 8,
      gold: 20,
      color: '#C0C0C0',
      radius: 13,
      flying: false,
    },
    healer: {
      name: 'Healer',
      hp: 60,
      speed: 55,
      armor: 0,
      gold: 15,
      color: '#44CC44',
      radius: 9,
      flying: false,
      special: 'heal',
      healRate: 5,
      healRange: 60,
    },
    flyer: {
      name: 'Flyer',
      hp: 70,
      speed: 70,
      armor: 0,
      gold: 18,
      color: '#9966CC',
      radius: 9,
      flying: true,
    },
    shielded: {
      name: 'Shielded',
      hp: 100,
      speed: 50,
      armor: 0,
      gold: 15,
      color: '#4488CC',
      radius: 11,
      flying: false,
      special: 'shield',
      shieldHp: 80,
    },
    boss: {
      name: 'Boss',
      hp: 1500,
      speed: 30,
      armor: 15,
      gold: 100,
      color: '#CC2222',
      radius: 20,
      flying: false,
    },
  },

  // Targeting modes
  TARGET_MODES: ['first', 'last', 'strongest', 'weakest', 'nearest'],

  // Game speeds
  GAME_SPEEDS: [1, 2, 3],

  // Visual
  COLORS: {
    background: '#2d5a1b',
    path: '#8b7355',
    pathBorder: '#6b5335',
    buildable: '#3a6b24',
    buildableHover: 'rgba(255,255,255,0.15)',
    blocked: '#2d5a1b',
    entry: '#cc4444',
    exit: '#4444cc',
    healthBarBg: '#333333',
    healthBarFg: '#44cc44',
    healthBarLow: '#cc4444',
    shieldBar: '#4488FF',
    goldText: '#FFD700',
    uiBg: 'rgba(0,0,0,0.75)',
    uiBorder: '#666666',
    uiText: '#FFFFFF',
    uiTextDim: '#AAAAAA',
    rangeCircle: 'rgba(255,255,255,0.15)',
    rangeCircleInvalid: 'rgba(255,0,0,0.15)',
    placementValid: 'rgba(0,255,0,0.3)',
    placementInvalid: 'rgba(255,0,0,0.3)',
  },
};
